
modLoader="javafml"
loaderVersion="[47,)"

license="MIT"
issueTrackerURL="https://github.com/iljg/town-portal-potion/issues"

[[mods]]
modId=""
version="${mod_version}"
displayName="Town Portal Potion (Forge)"
displayURL="https://github.com/iljg/town-portal-potion/"
authors="iljg"
description='''Simpe potion that teleports player back to their bed/spawn'''

[[dependencies.townportalpotion]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.townportalpotion]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


